# Project
site_name: InvenTree Documentation
site_description: InvenTree - Open Source Inventory Management
site_author: InvenTree
google_analytics: ['UA-143467500-1', 'inventree-docs']

# Repository
repo_url: https://github.com/inventree/inventree-docs
repo_name: inventree/inventree-docs

# Theme
theme:
  name: material
  custom_dir: _includes/overrides
  palette:
    scheme: default
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.autohide
edit_uri: "" # Disable "Edit" button
extra_css:
  - stylesheets/extra.css
  - stylesheets/brands.css
  - stylesheets/regular.css
  - stylesheets/solid.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/fontawesome.js
  - javascripts/brands.js
  - javascripts/regular.js
  - javascripts/solid.js

# Navigation
nav:
  - InvenTree:
    - About InvenTree: index.md
    - Features: features.md
    - What's New: releases/new.md
    - FAQ: faq.md
    - Contribute: contribute.md
    - Credits: credits.md
  - Installation:
    - Introduction: start/intro.md
    - Configuration: start/config.md
    - Docker Installation: start/docker.md
    - Docker Development: start/docker_dev.md
    - Manual Installation: start/install.md
    - Development Server: start/development.md
    - Production Server: start/production.md
    - Updating: start/update.md
    - Migrating: start/migrate.md
  - Parts:
    - Parts: part/part.md
    - Part Views: part/views.md
    - Tracking: part/trackable.md
    - Parameters: part/parameter.md
    - Templates: part/template.md
    - Tests: part/test.md
    - Pricing: part/pricing.md
  - Stock:
    - Stock Items: stock/stock.md
    - Adjusting Stock: stock/adjust.md
    - Stocktake: stock/stocktake.md
    - Stock Expiry: stock/expiry.md
    - Stock Ownership: stock/owner.md
    - Test Results: stock/test.md
  - Build:
    - Build Orders: build/build.md
    - Bill of Materials: build/bom.md
    - Allocating Stock: build/allocate.md
  - Companies:
    - Suppliers: companies/supplier.md
    - Manufacturers: companies/manufacturer.md
    - Customers: companies/customer.md
    - Purchase Orders: companies/po.md
    - Sales Orders: companies/so.md
  - Report:
    - Templates: report/report.md
    - Labels: report/labels.md
    - Reports:
      - Test Reports: report/test.md
      - Packing List: report/pack.md
      - Build Order: report/build.md
      - Order: report/order.md
    - Barcodes: report/barcodes.md
  - Admin:
    - Admin Interface: admin/admin.md
    - User Permissions: admin/permissions.md
    - Export Data: admin/export.md
    - Import Data: admin/import.md
    - Python Shell: admin/shell.md
    - Error Logs: admin/logs.md
    - Email: admin/email.md
    - Background Tasks: admin/tasks.md
  - Extend:
    - API: extend/api.md
    - Python Interface: extend/python.md
    - Plugins: extend/plugins.md
    - Themes: extend/themes.md
    - Third-Party: extend/integrate.md
  - App:
    - InvenTree App: app/app.md
    - Barcodes: app/barcode.md
    - Parts: app/part.md
    - Stock: app/stock.md
    - Settings: app/settings.md
    - Privacy: app/privacy.md
    - Translation: app/translation.md
    - Suggestions: app/issues.md

# Plugins
plugins:
  - search
  - macros:
      include_dir: _includes

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Global Variables
extra:
  static_folder_source: ./InvenTree/InvenTree/static/
  static_folder_local_default: ./inventree_static/
