# Project
site_url: https://inventree.readthedocs.io
site_name: InvenTree Documentation
site_description: InvenTree - Open Source Inventory Management
site_author: InvenTree

# Repository
repo_url: https://github.com/inventree/inventree-docs
repo_name: inventree/inventree-docs

# Theme
theme:
  name: material
  custom_dir: _includes/overrides
  palette:
    scheme: default
    accent: light blue
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.autohide
edit_uri: "" # Disable "Edit" button
extra_css:
  - stylesheets/extra.css
  - stylesheets/brands.css
  - stylesheets/regular.css
  - stylesheets/solid.css
  - stylesheets/bootstrap.css
  - https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/fontawesome.js
  - javascripts/brands.js
  - javascripts/regular.js
  - javascripts/solid.js
  - https://code.jquery.com/jquery-3.6.0.js
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.js
  - https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js

# Navigation
nav:
  - InvenTree:
    - Features: features.md
    - In Development: upcoming.md
    - Release Notes: releases/release_notes.md
    - FAQ: faq.md
    - Contribute: contribute.md
    - Credits: credits.md
  - Install:
    - Introduction: start/intro.md
    - Configuration: start/config.md
    - Docker Setup: start/docker.md
    - Bare Metal Setup: start/install.md
    - Updating: start/update.md
    - Migrating: start/migrate.md
    - Demo Dataset: start/demo.md
  - Parts:
    - Parts: part/part.md
    - Creating Parts: part/create.md
    - Part Views: part/views.md
    - Tracking: part/trackable.md
    - Parameters: part/parameter.md
    - Templates: part/template.md
    - Tests: part/test.md
    - Pricing: part/pricing.md
  - Stock:
    - Stock Items: stock/stock.md
    - Stock Status: stock/status.md
    - Adjusting Stock: stock/adjust.md
    - Stocktake: stock/stocktake.md
    - Stock Expiry: stock/expiry.md
    - Stock Ownership: stock/owner.md
    - Test Results: stock/test.md
  - Build:
    - Build Orders: build/build.md
    - Bill of Materials: build/bom.md
    - Allocating Stock: build/allocate.md
  - Companies:
    - Suppliers: companies/supplier.md
    - Manufacturers: companies/manufacturer.md
    - Customers: companies/customer.md
    - Purchase Orders: companies/po.md
    - Sales Orders: companies/so.md
  - Report:
    - Templates: report/report.md
    - Labels: report/labels.md
    - Reports:
      - Test Reports: report/test.md
      - Packing List: report/pack.md
      - Build Order: report/build.md
      - Order: report/order.md
    - Barcodes: report/barcodes.md
    - Context Variables: report/context_variables.md
  - Admin:
    - Admin Interface: admin/admin.md
    - User Permissions: admin/permissions.md
    - Export Data: admin/export.md
    - Import Data: admin/import.md
    - Python Shell: admin/shell.md
    - Error Logs: admin/logs.md
    - Email: admin/email.md
    - Background Tasks: admin/tasks.md
  - Extend:
    - API: extend/api.md
    - Python Interface: extend/python.md
    - Plugins: extend/plugins.md
    - Themes: extend/themes.md
    - Third-Party: extend/integrate.md
  - App:
    - InvenTree App: app/app.md
    - Connect: app/connect.md
    - Barcodes: app/barcode.md
    - Parts: app/part.md
    - Stock: app/stock.md
    - Settings: app/settings.md
    - Privacy: app/privacy.md
    - Release Notes: app/release.md
    - Translation: app/translation.md
    - Suggestions: app/issues.md

# Plugins
plugins:
  - search
  - git-revision-date-localized
  - macros:
      include_dir: _includes

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Global Variables
extra:
  static_folder_source: ./InvenTree/InvenTree/static/
  static_folder_local_default: ./inventree_static/

  # Site Analytics
  # See https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
  analytics:
    provider: google
    property: UA-143467500-1

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inventree/inventree
      name: InvenTree on GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/inventree/inventree
      name: InvenTree on Docker

use_directory_urls: true
strict: true
