# Project
site_name: InvenTree Documentation
site_description: InvenTree - Open Source Inventory Management
site_author: InvenTree
google_analytics: ['UA-143467500-1', 'inventree-docs']

# Repository
repo_url: https://github.com/inventree/inventree-docs
repo_name: inventree/inventree-docs

# Theme
theme:
  name: material
  custom_dir: _includes/overrides
  palette:
    scheme: default
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.autohide
edit_uri: "" # Disable "Edit" button
extra_css:
  - stylesheets/extra.css
  - stylesheets/brands.css
  - stylesheets/regular.css
  - stylesheets/solid.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/fontawesome.js
  - javascripts/brands.js
  - javascripts/regular.js
  - javascripts/solid.js

# Navigation
nav:
  - InvenTree:
    - About InvenTree: index.md
    - What's New: releases/new.md
    - Contribute: contribute.md
  - Getting Started:
    - Installation: start/install.md
    - Configuration: start/config.md
    - Deploying: start/deploy.md
    - Updating: start/update.md
    - Migrating: start/migrate.md
  - Parts:
    - Parts: part/part.md
    - Part Views: part/views.md
    - Tracking: part/trackable.md
    - Parameters: part/parameter.md
    - Templates: part/template.md
    - Tests: part/test.md
  - Stock:
    - Stock Items: stock/stock.md
    - Adjusting Stock: stock/adjust.md
    - Stocktake: stock/stocktake.md
    - Test Results: stock/test.md
  - Build:
    - Build Parts: build/build.md
    - Bill of Materials (BOM): build/bom.md
  - Companies:
    - Suppliers: companies/supplier.md
    - Manufacturers: companies/manufacturer.md
    - Customers: companies/customer.md
    - Purchase Orders: companies/po.md
    - Sales Orders: companies/so.md
  - Report:
    - Labels: report/labels.md
    - Templates: report/report.md
    - Test Reports: report/test.md
    - Packing List: report/pack.md
    - Order: report/order.md
  - Admin:
    - Admin Interface: admin/admin.md
    - User Permissions: admin/permissions.md
    - Export Data: admin/export.md
    - Import Data: admin/import.md
    - Python Shell: admin/shell.md
    - Error Logs: admin/logs.md
  - Extend:
    - API: extend/api.md
    - Python Interface: extend/python.md
    - Plugins: extend/plugins.md
    - Themes: extend/themes.md
    - Third-Party: extend/integrate.md
    - Future Features: extend/future.md

# Plugins
plugins:
  - search
  - macros:
      include_dir: _includes

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Global Variables
extra:
  static_folder_source: ./InvenTree/InvenTree/static/
  static_folder_local_default: ./inventree_static/
